language: dart

dart:
  - dev
  - stable

dart_task:
  - test: -x presubmit-only
  - test: --run-skipped -t presubmit-only
  - dartfmt

matrix:
  include:
    - dart: dev
      dart_task:
        dartanalyzer: --fatal-infos --fatal-warnings .
    - dart: stable
      dart_task:
        dartanalyzer: --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
