# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `pub run build_runner build`
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/src/pubspec.dart
          - lib/src/dependency.dart
        options:
          any_map: true
          checked: true
